load("//bazel/mcu:clangd_rules.bzl", "mcu_compile_commands")
load("//bazel/mcu:mcu_rules.bzl", "mcu_firmware_package", "mcu_full_image", "mcu_ota_app_image")

package(default_visibility = ["//visibility:public"])

mcu_full_image(
    name = "full",
    app = "//stm32f103:motor",
    boot = "//boot:boot",
)

mcu_ota_app_image(
    name = "ota_app",
    app = "//stm32f103:motor",
)

mcu_firmware_package(
    name = "firmware_package",
    app = "//stm32f103:motor",
    boot = "//boot:boot",
    full = ":full",
    ota_app = ":ota_app",
    package_name = "motor_duck",
    version_header = "//user/app:app_version.h",
)

mcu_compile_commands(
    name = "app_clangd_compile_commands",
    firmware = "//stm32f103:motor",
)

mcu_compile_commands(
    name = "boot_clangd_compile_commands",
    firmware = "//boot:boot",
)

filegroup(
    name = "firmware",
    srcs = [
        ":firmware_package",
        ":full",
        ":ota_app",
        "//boot:boot",
        "//stm32f103:motor",
    ],
)
