#ifndef FLASH_LAYOUT_H
#define FLASH_LAYOUT_H

#ifdef __cplusplus
extern "C" {
#endif

#define FLASH_LAYOUT_FLASH_BASE_ADDRESS      0x08000000u
#define FLASH_LAYOUT_BOOT_SIZE               0x00004400u
#define FLASH_LAYOUT_APP_ADDRESS             0x08004400u
#define FLASH_LAYOUT_OTA_INFO_ADDRESS        0x0800F800u
#define FLASH_LAYOUT_USER_INFO_ADDRESS       0x0800FC00u
#define FLASH_LAYOUT_FLASH_PAGE_SIZE         1024u
#define FLASH_LAYOUT_APP_SIZE                (FLASH_LAYOUT_OTA_INFO_ADDRESS - FLASH_LAYOUT_APP_ADDRESS)
#define FLASH_LAYOUT_OTA_INFO_OFFSET         (FLASH_LAYOUT_OTA_INFO_ADDRESS - FLASH_LAYOUT_FLASH_BASE_ADDRESS)
#define FLASH_LAYOUT_USER_INFO_OFFSET        (FLASH_LAYOUT_USER_INFO_ADDRESS - FLASH_LAYOUT_FLASH_BASE_ADDRESS)

#ifdef __cplusplus
}
#endif

#endif /* FLASH_LAYOUT_H */
