load("//bazel/mcu:mcu_rules.bzl", "mcu_library")

package(default_visibility = ["//visibility:public"])

mcu_library(
    name = "user_app",
    srcs = [
        "app_light.c",
        "app_version.c",
        "as5600.c",
        "can_protocol.c",
        "flash.c",
        "foc_app.c",
        "foc_config.c",
        "hardware_iic.c",
        "log.c",
        "motor_music.c",
        "user_main.c",
    ],
    hdrs = glob(["*.h"]),
    includes = ["user"],
    deps = [
        "//user/common:user_info",
        "//user/foc:user_foc",
        "//user/kernel:user_kernel",
        "//user/rtt:user_rtt",
    ],
)
